{
 "title": "Learning Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Jobs Complete Postgres",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jobs_complete", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs Pending Postgres",
   "type": "stat",
   "description": "Number of jobs in Postgres marked as pending.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jobs_pending", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Queue Depth",
   "type": "stat",
   "description": "Number of pending jobs in the redis queue yet to be processed by the server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_depth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}